In [2]:
import pandas as pd

In [3]:
df = pd.read_csv(r'D:\UCS-Satellite-Database-Officialname-1-1-2023.csv',encoding='latin1')

In [4]:
df.head()

,Current Official Name of Satellite,Country/Org of UN Registry,Country of Operator/Owner,Operator/Owner,Users,Purpose,Detailed Purpose,Class of Orbit,Type of Orbit,Longitude of GEO (degrees),...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
0,1HOPSAT-TD,NR,USA,Hera Systems,Commercial,Earth Observation,Infrared Imaging,LEO,Non-Polar Inclined,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aalto-1,Finland,Finland,Aalto University,Civil,Technology Development,NaN,LEO,Sun-Synchronous,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AAt-4,Denmark,Denmark,University of Aalborg,Civil,Earth Observation,Automatic Identification System (AIS),LEO,Sun-Synchronous,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABS-2,NR,Multinational,Asia Broadcast Satellite Ltd.,Commercial,Communications,NaN,GEO,NaN,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ABS-2A,NR,Multinational,Asia Broadcast Satellite Ltd.,Commercial,Communications,NaN,GEO,NaN,-75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.head()

,Current Official Name of Satellite,Country/Org of UN Registry,Country of Operator/Owner,Operator/Owner,Users,Purpose,Detailed Purpose,Class of Orbit,Type of Orbit,Longitude of GEO (degrees),...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
0,1HOPSAT-TD,NR,USA,Hera Systems,Commercial,Earth Observation,Infrared Imaging,LEO,Non-Polar Inclined,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Aalto-1,Finland,Finland,Aalto University,Civil,Technology Development,NaN,LEO,Sun-Synchronous,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,AAt-4,Denmark,Denmark,University of Aalborg,Civil,Earth Observation,Automatic Identification System (AIS),LEO,Sun-Synchronous,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,ABS-2,NR,Multinational,Asia Broadcast Satellite Ltd.,Commercial,Communications,NaN,GEO,NaN,75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,ABS-2A,NR,Multinational,Asia Broadcast Satellite Ltd.,Commercial,Communications,NaN,GEO,NaN,-75.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.columns

Index(['Current Official Name of Satellite', 'Country/Org of UN Registry',
       'Country of Operator/Owner', 'Operator/Owner', 'Users', 'Purpose',
       'Detailed Purpose', 'Class of Orbit', 'Type of Orbit',
       'Longitude of GEO (degrees)', 'Perigee (km)', 'Apogee (km)',
       'Eccentricity', 'Inclination (degrees)', 'Period (minutes)',
       'Launch Mass (kg.)', ' Dry Mass (kg.) ', 'Power (watts)',
       'Date of Launch', 'Expected Lifetime (yrs.)', 'Contractor',
       'Country of Contractor', 'Launch Site', 'Launch Vehicle',
       'COSPAR Number', 'NORAD Number', 'Comments', 'Unnamed: 27',
       'Source Used for Orbital Data', 'Source', 'Source.1', 'Source.2',
       'Source.3', 'Source.4', 'Source.5', 'Source.6', 'Unnamed: 36',
       'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40',
       'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44',
       'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48',
       'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52',
       'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56',
       'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60',
       'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64',
       'Unnamed: 65', 'Unnamed: 66'],
      dtype='object')

In [9]:
df.dtypes

Current Official Name of Satellite    object
Country/Org of UN Registry            object
Country of Operator/Owner             object
Operator/Owner                        object
Users                                 object
                                       ...
Unnamed: 62                           object
Unnamed: 63                           object
Unnamed: 64                           object
Unnamed: 65                           object
Unnamed: 66                           object
Length: 67, dtype: object

In [10]:
df.info

<bound method DataFrame.info of      Current Official Name of Satellite Country/Org of UN Registry  \
0                            1HOPSAT-TD                         NR
1                               Aalto-1                    Finland
2                                 AAt-4                    Denmark
3                                 ABS-2                         NR
4                                ABS-2A                         NR
...                                 ...                        ...
6713                        Ziyuan 1-2D                         NR
6714                           Ziyuan 3                      China
6715                         Ziyuan 3-2                      China
6716                         Ziyuan 3-3                      China
6717                              Z-Sat                  NR (1/22)

     Country of Operator/Owner  \
0                          USA
1                      Finland
2                      Denmark
3                Multinational
4                Multinational
...                        ...
6713                     China
6714                     China
6715                     China
6716                     China
6717                     Japan

                                         Operator/Owner       Users  \
0                                          Hera Systems  Commercial
1                                      Aalto University       Civil
2                                 University of Aalborg       Civil
3                         Asia Broadcast Satellite Ltd.  Commercial
4                         Asia Broadcast Satellite Ltd.  Commercial
...                                                 ...         ...
6713  China Centre for Resources Satellite Data and ...  Government
6714  China Centre for Resources Satellite Data and ...  Government
6715  China Centre for Resources Satellite Data and ...  Government
6716  China Centre for Resources Satellite Data and ...  Government
6717                        Mitsubishi Heavy Industries  Commercial

                     Purpose                       Detailed Purpose  \
0          Earth Observation                       Infrared Imaging
1     Technology Development                                    NaN
2          Earth Observation  Automatic Identification System (AIS)
3             Communications                                    NaN
4             Communications                                    NaN
...                      ...                                    ...
6713       Earth Observation                  Hyperspectral Imaging
6714       Earth Observation                        Optical Imaging
6715       Earth Observation                        Optical Imaging
6716       Earth Observation                        Optical Imaging
6717  Technology Development                                    NaN

     Class of Orbit       Type of Orbit  Longitude of GEO (degrees)  ...  \
0               LEO  Non-Polar Inclined                         0.0  ...
1               LEO     Sun-Synchronous                         0.0  ...
2               LEO     Sun-Synchronous                         0.0  ...
3               GEO                 NaN                        75.0  ...
4               GEO                 NaN                       -75.0  ...
...             ...                 ...                         ...  ...
6713            LEO     Sun-Synchronous                         0.0  ...
6714            LEO     Sun-Synchronous                         0.0  ...
6715            LEO     Sun-Synchronous                         0.0  ...
6716            LEO     Sun-Synchronous                         0.0  ...
6717            LEO     Sun-Synchronous                         0.0  ...

     Unnamed: 57 Unnamed: 58  Unnamed: 59 Unnamed: 60 Unnamed: 61 Unnamed: 62  \
0            NaN         NaN          NaN         NaN         NaN         NaN
1            NaN         NaN          NaN         NaN         NaN         NaN
2            NaN         NaN          NaN         NaN         NaN         NaN
3            NaN         NaN          NaN         NaN         NaN         NaN
4            NaN         NaN          NaN         NaN         NaN         NaN
...          ...         ...          ...         ...         ...         ...
6713         NaN         NaN          NaN         NaN         NaN         NaN
6714         NaN         NaN          NaN         NaN         NaN         NaN
6715         NaN         NaN          NaN         NaN         NaN         NaN
6716         NaN         NaN          NaN         NaN         NaN         NaN
6717         NaN         NaN          NaN         NaN         NaN         NaN

     Unnamed: 63 Unnamed: 64 Unnamed: 65  Unnamed: 66
0            NaN         NaN         NaN          NaN
1            NaN         NaN         NaN          NaN
2            NaN         NaN         NaN          NaN
3            NaN         NaN         NaN          NaN
4            NaN         NaN         NaN          NaN
...          ...         ...         ...          ...
6713         NaN         NaN         NaN          NaN
6714         NaN         NaN         NaN          NaN
6715         NaN         NaN         NaN          NaN
6716         NaN         NaN         NaN          NaN
6717         NaN         NaN         NaN          NaN

[6718 rows x 67 columns]>

In [11]:
df.describe()

,Longitude of GEO (degrees),Eccentricity,Expected Lifetime (yrs.),NORAD Number
count,6716.000000,6718.000000,4804.000000,6718.000000
mean,1.844772,0.391619,5.510148,46818.601518
std,27.608673,14.122881,3.592762,6281.113629
min,-179.800000,-0.033400,0.250000,7530.000000
25%,0.000000,0.000202,4.000000,44068.000000
50%,0.000000,0.000329,4.000000,47806.500000
75%,0.000000,0.000943,5.000000,51975.750000
max,359.000000,575.000000,30.000000,62684.000000

In [12]:
df.isnull()

,Current Official Name of Satellite,Country/Org of UN Registry,Country of Operator/Owner,Operator/Owner,Users,Purpose,Detailed Purpose,Class of Orbit,Type of Orbit,Longitude of GEO (degrees),...,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64,Unnamed: 65,Unnamed: 66
0,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
1,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,True,True,True,True,True,True
2,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
3,False,False,False,False,False,False,True,False,True,False,...,True,True,True,True,True,True,True,True,True,True
4,False,False,False,False,False,False,True,False,True,False,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6713,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
6714,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
6715,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
6716,False,False,False,False,False,False,False,False,False,False,...,True,True,True,True,True,True,True,True,True,True
6717,False,False,False,False,False,False,True,False,False,False,...,True,True,True,True,True,True,True,True,True,True

In [13]:
df.isnull().sum()

Current Official Name of Satellite       0
Country/Org of UN Registry               0
Country of Operator/Owner                0
Operator/Owner                           0
Users                                    0
                                      ...
Unnamed: 62                           6234
Unnamed: 63                           6234
Unnamed: 64                           6234
Unnamed: 65                           6232
Unnamed: 66                           6234
Length: 67, dtype: int64

In [18]:
df.columns

Index(['Current Official Name of Satellite', 'Country/Org of UN Registry',
       'Country of Operator/Owner', 'Operator/Owner', 'Users', 'Purpose',
       'Detailed Purpose', 'Class of Orbit', 'Type of Orbit',
       'Longitude of GEO (degrees)', 'Perigee (km)', 'Apogee (km)',
       'Eccentricity', 'Inclination (degrees)', 'Period (minutes)',
       'Launch Mass (kg.)', ' Dry Mass (kg.) ', 'Power (watts)',
       'Date of Launch', 'Expected Lifetime (yrs.)', 'Contractor',
       'Country of Contractor', 'Launch Site', 'Launch Vehicle',
       'COSPAR Number', 'NORAD Number', 'Comments', 'Unnamed: 27',
       'Source Used for Orbital Data', 'Source', 'Source.1', 'Source.2',
       'Source.3', 'Source.4', 'Source.5', 'Source.6', 'Unnamed: 36',
       'Unnamed: 37', 'Unnamed: 38', 'Unnamed: 39', 'Unnamed: 40',
       'Unnamed: 41', 'Unnamed: 42', 'Unnamed: 43', 'Unnamed: 44',
       'Unnamed: 45', 'Unnamed: 46', 'Unnamed: 47', 'Unnamed: 48',
       'Unnamed: 49', 'Unnamed: 50', 'Unnamed: 51', 'Unnamed: 52',
       'Unnamed: 53', 'Unnamed: 54', 'Unnamed: 55', 'Unnamed: 56',
       'Unnamed: 57', 'Unnamed: 58', 'Unnamed: 59', 'Unnamed: 60',
       'Unnamed: 61', 'Unnamed: 62', 'Unnamed: 63', 'Unnamed: 64',
       'Unnamed: 65', 'Unnamed: 66'],
      dtype='object')

In [25]:
df['Launch Mass (kg.)'].sort_values(ascending = False).head(1)

864    980
Name: Launch Mass (kg.), dtype: object

In [ ]:
Find the satellite with the lowest mass.
Find the satellite with the highest altitude/apogee.
Find the satellite with the lowest altitude/perigee.
Find the satellites with the longest expected lifetime.
Find the 20 newest satellites.
Find the 20 oldest satellites.
Sort satellites by mass.
Sort satellites by orbital period.
Find satellites above a specified altitude.
Find satellites below a specified altitude.
Filter satellites belonging to a particular purpose/type.

In [28]:
df['Launch Mass (kg.)'].sort_values(ascending = True).head(1)

330     10
Name: Launch Mass (kg.), dtype: object

In [30]:
df['Apogee (km)'].sort_values(ascending = False).head(1)

1366    997
Name: Apogee (km), dtype: object

In [33]:
df['Perigee (km)'].sort_values().head(1)

2828    1,000
Name: Perigee (km), dtype: object