In [2]:
import pandas as pd

In [3]:
df = pd.read_excel(r"D:\Global Superstore Data.xlsx")
pd.set_option('display.max_columns',200)

In [3]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Postal Code', 'City',
       'State', 'Country', 'Region', 'Market', 'Product ID', 'Product Name',
       'Sub-Category', 'Category', 'Sales', 'Quantity', 'Discount', 'Profit',
       'Shipping Cost', 'Order Priority'],
      dtype='object')

In [8]:
df.loc[df['Category'] == 'Technology']

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Product Name,Sub-Category,Category,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
2,24598,IN-2017-CA120551-42816,2017-03-22,2017-03-29,Standard Class,CA-120551,Cathy Armstrong,Home Office,NaN,Herat,...,TEC-MA-4211,"Epson Receipt Printer, White",Machines,Technology,346.320,3,0.0,13.770,14.10,Medium
8,29492,IN-2016-LO171701-42637,2016-09-24,2016-09-28,Standard Class,LO-171701,Lori Olson,Corporate,NaN,Kabul,...,TEC-PH-5814,"Samsung Audio Dock, VoIP",Phones,Technology,1168.440,7,0.0,443.940,92.34,Medium
9,28966,IN-2017-VB217451-43080,2017-12-11,2017-12-15,Standard Class,VB-217451,Victoria Brennan,Corporate,NaN,Kabul,...,TEC-PH-3129,"Apple Audio Dock, VoIP",Phones,Technology,500.940,3,0.0,115.200,79.59,High
12,29094,IN-2015-BG110351-42275,2015-09-28,2015-10-04,Standard Class,BG-110351,Barry Gonzalez,Consumer,NaN,Kabul,...,TEC-CO-4588,"Hewlett Personal Copier, High-Speed",Copiers,Technology,427.410,3,0.0,4.230,60.91,Low
16,29096,IN-2015-BG110351-42275,2015-09-28,2015-10-04,Standard Class,BG-110351,Barry Gonzalez,Consumer,NaN,Kabul,...,TEC-PH-5251,"Motorola Headset, Cordless",Phones,Technology,412.950,5,0.0,24.750,42.28,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51221,49526,ZA-2015-DR2880147-42162,2015-06-07,2015-06-09,First Class,DR-2880147,Dan Reichenbach,Corporate,NaN,Bulawayo,...,TEC-PH-5827,"Samsung Headset, with Caller ID",Phones,Technology,21.960,1,0.7,-47.580,2.85,Medium
51224,42069,ZA-2017-BS1380147-42818,2017-03-24,2017-03-28,Standard Class,BS-1380147,Bill Stewart,Corporate,NaN,Bulawayo,...,TEC-MA-6144,"StarTech Phone, Red",Machines,Technology,21.501,1,0.7,-20.799,2.25,Medium
51246,42926,ZA-2015-DN3690147-42159,2015-06-04,2015-06-07,Second Class,DN-3690147,Duane Noonan,Consumer,NaN,Chitungwiza,...,TEC-CO-4780,"HP Ink, Laser",Copiers,Technology,154.440,4,0.7,-257.400,23.01,High
51276,48014,ZA-2017-NG8430147-43063,2017-11-24,2017-11-30,Standard Class,NG-8430147,Nathan Gelder,Consumer,NaN,Harare,...,TEC-MA-5494,"Okidata Calculator, Red",Machines,Technology,14.832,1,0.7,-20.298,1.93,Medium
51288,47164,ZA-2015-JG5115147-42040,2015-02-05,2015-02-10,Standard Class,JG-5115147,Jack Garza,Consumer,NaN,Kadoma,...,TEC-MA-5542,"Panasonic Card Printer, Durable",Machines,Technology,104.364,2,0.7,-173.976,7.46,Medium

In [13]:
df['Postal Code'] = df['Postal Code'].fillna('NULL')
df.head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,...,Product ID,Product Name,Sub-Category,Category,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
0,24599,IN-2017-CA120551-42816,2017-03-22,2017-03-29,Standard Class,CA-120551,Cathy Armstrong,Home Office,NULL,Herat,...,FUR-BO-4861,"Ikea Library with Doors, Mobile",Bookcases,Furniture,731.82,2,0.0,102.42,39.66,Medium
1,29465,ID-2015-BD116051-42248,2015-09-01,2015-09-04,Second Class,BD-116051,Brian Dahlen,Consumer,NULL,Herat,...,OFF-SU-2988,"Acme Scissors, Easy Grip",Supplies,Office Supplies,243.54,9,0.0,104.49,18.72,Medium
2,24598,IN-2017-CA120551-42816,2017-03-22,2017-03-29,Standard Class,CA-120551,Cathy Armstrong,Home Office,NULL,Herat,...,TEC-MA-4211,"Epson Receipt Printer, White",Machines,Technology,346.32,3,0.0,13.77,14.10,Medium
3,24597,IN-2017-CA120551-42816,2017-03-22,2017-03-29,Standard Class,CA-120551,Cathy Armstrong,Home Office,NULL,Herat,...,FUR-FU-5726,"Rubbermaid Door Stop, Erganomic",Furnishings,Furniture,169.68,4,0.0,79.68,11.01,Medium
4,29464,ID-2015-BD116051-42248,2015-09-01,2015-09-04,Second Class,BD-116051,Brian Dahlen,Consumer,NULL,Herat,...,OFF-EN-3664,"Cameo Interoffice Envelope, with clear poly wi...",Envelopes,Office Supplies,203.88,4,0.0,24.36,5.72,Medium
5,28879,ID-2015-AJ107801-42113,2015-04-19,2015-04-22,First Class,AJ-107801,Anthony Jacobs,Corporate,NULL,Kabul,...,FUR-TA-3420,"Bevis Conference Table, Fully Assembled",Tables,Furniture,4626.15,5,0.0,647.55,835.57,High
6,27993,IN-2017-GM144551-42948,2017-08-01,2017-08-05,Standard Class,GM-144551,Gary Mitchum,Home Office,NULL,Kabul,...,FUR-BO-3626,"Bush Classic Bookcase, Pine",Bookcases,Furniture,2070.15,5,0.0,848.70,185.01,Medium
7,28967,IN-2017-VB217451-43080,2017-12-11,2017-12-15,Standard Class,VB-217451,Victoria Brennan,Corporate,NULL,Kabul,...,FUR-CH-4683,"Hon Rocking Chair, Red",Chairs,Furniture,914.34,7,0.0,356.58,106.41,High
8,29492,IN-2016-LO171701-42637,2016-09-24,2016-09-28,Standard Class,LO-171701,Lori Olson,Corporate,NULL,Kabul,...,TEC-PH-5814,"Samsung Audio Dock, VoIP",Phones,Technology,1168.44,7,0.0,443.94,92.34,Medium
9,28966,IN-2017-VB217451-43080,2017-12-11,2017-12-15,Standard Class,VB-217451,Victoria Brennan,Corporate,NULL,Kabul,...,TEC-PH-3129,"Apple Audio Dock, VoIP",Phones,Technology,500.94,3,0.0,115.20,79.59,High

In [23]:
df.loc[(df['Segment'] == 'Consumer') & (df['Sales']>500)]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,State,Country,Region,Market,Product ID,Product Name,Sub-Category,Category,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
11,23222,IN-2017-AA103751-42926,2017-07-10,2017-07-15,Second Class,AA-103751,Allen Armold,Consumer,NaN,Kabul,Kabul,Afghanistan,Southern Asia,Asia Pacific,OFF-AP-4747,"Hoover Toaster, Red",Appliances,Office Supplies,669.12,8,0.0,280.80,72.67,High
71,50118,AG-2014-RO97803-41695,2014-02-25,2014-02-25,Same Day,RO-97803,Rose O'Brian,Consumer,NaN,Algiers,Alger,Algeria,North Africa,Africa,TEC-MA-4197,"Epson Inkjet, Durable",Machines,Technology,613.26,2,0.0,202.32,241.33,Critical
72,45891,AG-2015-TS115053-42337,2015-11-29,2015-12-02,First Class,TS-115053,Tony Sayre,Consumer,NaN,Algiers,Alger,Algeria,North Africa,Africa,FUR-BO-3901,"Dania Library with Doors, Metal",Bookcases,Furniture,1447.44,4,0.0,506.52,199.04,Medium
77,47787,AG-2016-SK99903-42612,2016-08-30,2016-09-02,Second Class,SK-99903,Sally Knutson,Consumer,NaN,Algiers,Alger,Algeria,North Africa,Africa,OFF-ST-6248,"Tenex File Cart, Single Width",Storage,Office Supplies,538.44,4,0.0,252.96,40.92,High
126,46335,AG-2014-EG39003-41992,2014-12-19,2014-12-26,Standard Class,EG-39003,Emily Grady,Consumer,NaN,Annaba,Annaba,Algeria,North Africa,Africa,OFF-AP-3864,"Cuisinart Microwave, Black",Appliances,Office Supplies,1111.56,4,0.0,55.56,162.67,Low
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51163,41793,ZA-2014-NF8385146-41986,2014-12-13,2014-12-18,Standard Class,NF-8385146,Natalie Fritzler,Consumer,NaN,Lusaka,Lusaka,Zambia,Eastern Africa,Africa,TEC-CO-3598,"Brother Fax Machine, Laser",Copiers,Technology,637.08,2,0.0,261.18,141.20,High
51166,42448,ZA-2017-DB3615146-42993,2017-09-15,2017-09-21,Standard Class,DB-3615146,Doug Bickford,Consumer,NaN,Lusaka,Lusaka,Zambia,Eastern Africa,Africa,FUR-BO-4863,"Ikea Library with Doors, Traditional",Bookcases,Furniture,2180.34,6,0.0,959.22,112.59,Medium
51167,47247,ZA-2016-JK5730146-42617,2016-09-04,2016-09-10,Standard Class,JK-5730146,Joe Kamberova,Consumer,NaN,Lusaka,Lusaka,Zambia,Eastern Africa,Africa,OFF-ST-4057,"Eldon File Cart, Single Width",Storage,Office Supplies,1023.36,8,0.0,184.08,110.53,Medium
51168,41867,ZA-2015-IG5085146-42167,2015-06-12,2015-06-18,Standard Class,IG-5085146,Ivan Gibson,Consumer,NaN,Lusaka,Lusaka,Zambia,Eastern Africa,Africa,TEC-MA-5578,"Panasonic Receipt Printer, Wireless",Machines,Technology,967.20,8,0.0,251.28,91.24,Low
51174,47244,ZA-2016-JK5730146-42617,2016-09-04,2016-09-10,Standard Class,JK-5730146,Joe Kamberova,Consumer,NaN,Lusaka,Lusaka,Zambia,Eastern Africa,Africa,OFF-AP-4736,"Hoover Refrigerator, Red",Appliances,Office Supplies,526.26,1,0.0,131.55,20.69,Medium

In [27]:
df.loc[df['Ship Mode'] == 'First Class']

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,State,Country,Region,Market,Product ID,Product Name,Sub-Category,Category,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
5,28879,ID-2015-AJ107801-42113,2015-04-19,2015-04-22,First Class,AJ-107801,Anthony Jacobs,Corporate,NaN,Kabul,Kabul,Afghanistan,Southern Asia,Asia Pacific,FUR-TA-3420,"Bevis Conference Table, Fully Assembled",Tables,Furniture,4626.150,5,0.0,647.550,835.57,High
14,27278,IN-2016-CS118451-42387,2016-01-18,2016-01-20,First Class,CS-118451,Cari Sayre,Corporate,NaN,Kabul,Kabul,Afghanistan,Southern Asia,Asia Pacific,OFF-ST-6068,"Smead Trays, Wire Frame",Storage,Office Supplies,332.850,7,0.0,59.850,53.01,High
15,27279,IN-2016-CS118451-42387,2016-01-18,2016-01-20,First Class,CS-118451,Cari Sayre,Corporate,NaN,Kabul,Kabul,Afghanistan,Southern Asia,Asia Pacific,FUR-TA-3758,"Chromcraft Coffee Table, with Bottom Storage",Tables,Furniture,267.090,1,0.0,34.710,50.01,High
18,28276,IN-2014-AH105851-41973,2014-11-30,2014-12-03,First Class,AH-105851,Angele Hood,Consumer,NaN,Kabul,Kabul,Afghanistan,Southern Asia,Asia Pacific,FUR-FU-5727,"Rubbermaid Frame, Black",Furnishings,Furniture,219.780,2,0.0,59.340,36.24,Critical
20,23951,IN-2014-RS194201-41867,2014-08-16,2014-08-18,First Class,RS-194201,Ricardo Sperren,Corporate,NaN,Kabul,Kabul,Afghanistan,Southern Asia,Asia Pacific,OFF-PA-5890,"SanDisk Parchment Paper, 8.5 x 11",Paper,Office Supplies,83.400,4,0.0,8.280,21.21,Critical
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51271,48018,ZA-2016-DB3210147-42472,2016-04-12,2016-04-15,First Class,DB-3210147,Dean Braden,Consumer,NaN,Harare,Harare,Zimbabwe,Eastern Africa,Africa,OFF-AR-5925,"Sanford Pens, Easy-Erase",Art,Office Supplies,20.466,6,0.7,-32.094,4.49,High
51273,42718,ZA-2017-GR4560147-42947,2017-07-31,2017-08-01,First Class,GR-4560147,Georgia Rosenberg,Corporate,NaN,Harare,Harare,Zimbabwe,Eastern Africa,Africa,FUR-BO-4859,"Ikea Floating Shelf Set, Traditional",Bookcases,Furniture,51.102,1,0.7,-109.038,3.26,Critical
51278,47082,ZA-2016-EM4140147-42411,2016-02-11,2016-02-13,First Class,EM-4140147,Eugene Moren,Home Office,NaN,Harare,Harare,Zimbabwe,Eastern Africa,Africa,OFF-BI-6374,"Wilson Jones Binder Covers, Clear",Binders,Office Supplies,3.195,1,0.7,-4.815,1.68,High
51280,47081,ZA-2016-EM4140147-42411,2016-02-11,2016-02-13,First Class,EM-4140147,Eugene Moren,Home Office,NaN,Harare,Harare,Zimbabwe,Eastern Africa,Africa,OFF-BI-6405,"Wilson Jones Index Tab, Recycled",Binders,Office Supplies,4.086,2,0.7,-5.754,1.42,High
51282,42683,ZA-2015-AB10060147-42239,2015-08-23,2015-08-24,First Class,AB-10060147,Adam Bellavance,Home Office,NaN,Harare,Harare,Zimbabwe,Eastern Africa,Africa,OFF-BI-3249,"Avery Binder Covers, Recycled",Binders,Office Supplies,6.858,2,0.7,-7.782,1.16,Medium

In [29]:
df.loc[df['Order Date'] == '2015']

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,State,Country,Region,Market,Product ID,Product Name,Sub-Category,Category,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
7833,28455,IN-2015-ML1741027-42005,2015-01-01,2015-01-05,Standard Class,ML-1741027,Maris LaWare,Consumer,NaN,Baotou,Inner Mongolia,China,Eastern Asia,Asia Pacific,TEC-MA-4198,"Epson Inkjet, White",Machines,Technology,916.1100,3,0.00,36.6300,49.900,Medium
12326,9931,MX-2015-BD1172539-42005,2015-01-01,2015-01-03,First Class,BD-1172539,Bruce Degenhardt,Consumer,NaN,Soyapango,San Salvador,El Salvador,Central America,LATAM,OFF-ST-4285,"Fellowes Shelving, Wire Frame",Storage,Office Supplies,417.3400,11,0.00,208.5600,117.537,High
13058,14452,ES-2015-JP1546045-42005,2015-01-01,2015-01-05,Standard Class,JP-1546045,Jennifer Patt,Corporate,NaN,Givors,Auvergne-Rhône-Alpes,France,Western Europe,Europe,OFF-FA-5481,"OIC Staples, Assorted Sizes",Fasteners,Office Supplies,26.3700,3,0.00,9.9900,1.710,Medium
18500,7073,US-2015-KC1667555-42005,2015-01-01,2015-01-05,Standard Class,KC-1667555,Kimberly Carter,Corporate,NaN,San Pedro Sula,Cortés,Honduras,Central America,LATAM,FUR-TA-3759,"Chromcraft Computer Table, Adjustable Height",Tables,Furniture,178.2480,2,0.70,-154.5120,28.412,High
18506,7074,US-2015-KC1667555-42005,2015-01-01,2015-01-05,Standard Class,KC-1667555,Kimberly Carter,Corporate,NaN,San Pedro Sula,Cortés,Honduras,Central America,LATAM,TEC-AC-5897,"SanDisk Router, USB",Accessories,Technology,102.6240,1,0.40,-30.7960,22.219,High
18625,7072,US-2015-KC1667555-42005,2015-01-01,2015-01-05,Standard Class,KC-1667555,Kimberly Carter,Corporate,NaN,San Pedro Sula,Cortés,Honduras,Central America,LATAM,OFF-LA-4537,"Harbour Creations Legal Exhibit Labels, 5000 L...",Labels,Office Supplies,13.6080,3,0.40,-6.6120,1.522,High
19599,21980,IN-2015-MA1756058-42005,2015-01-01,2015-01-06,Standard Class,MA-1756058,Matt Abelman,Home Office,NaN,Bellary,Karnataka,India,Southern Asia,Asia Pacific,TEC-AC-5194,"Memorex Flash Drive, Erganomic",Accessories,Technology,244.8900,9,0.00,65.8800,24.560,High
20200,24876,IN-2015-AR1054058-42005,2015-01-01,2015-01-05,Standard Class,AR-1054058,Andy Reiter,Consumer,NaN,Jodhpur,Rajasthan,India,Southern Asia,Asia Pacific,TEC-PH-5351,"Nokia Signal Booster, Full Size",Phones,Technology,413.3700,3,0.00,115.7400,74.730,High
20212,24877,IN-2015-AR1054058-42005,2015-01-01,2015-01-05,Standard Class,AR-1054058,Andy Reiter,Consumer,NaN,Jodhpur,Rajasthan,India,Southern Asia,Asia Pacific,OFF-AR-3493,"Binney & Smith Pencil Sharpener, Fluorescent",Art,Office Supplies,26.6700,1,0.00,11.4600,1.500,High
21873,29626,ID-2015-JS1559559-42005,2015-01-01,2015-01-05,Standard Class,JS-1559559,Jill Stevenson,Corporate,NaN,Medan,Sumatera Utara,Indonesia,Southeastern Asia,Asia Pacific,OFF-AP-4745,"Hoover Stove, White",Appliances,Office Supplies,2821.7178,6,0.17,339.8778,301.260,High
21874,29624,ID-2015-JS1559559-42005,2015-01-01,2015-01-05,Standard Class,JS-1559559,Jill Stevenson,Corporate,NaN,Medan,Sumatera Utara,Indonesia,Southeastern Asia,Asia Pacific,OFF-ST-5702,"Rogers Lockers, Single Width",Storage,Office Supplies,1229.6865,7,0.17,399.9765,200.900,High
21884,29623,ID-2015-JS1559559-42005,2015-01-01,2015-01-05,Standard Class,JS-1559559,Jill Stevenson,Corporate,NaN,Medan,Sumatera Utara,Indonesia,Southeastern Asia,Asia Pacific,FUR-CH-4558,"Harbour Creations Steel Folding Chair, Black",Chairs,Furniture,627.1722,9,0.27,-51.6078,61.810,High
21886,29628,ID-2015-JS1559559-42005,2015-01-01,2015-01-05,Standard Class,JS-1559559,Jill Stevenson,Corporate,NaN,Medan,Sumatera Utara,Indonesia,Southeastern Asia,Asia Pacific,TEC-AC-4185,"Enermax Router, Bluetooth",Accessories,Technology,273.8298,2,0.47,-77.5302,42.620,High
21898,29625,ID-2015-JS1559559-42005,2015-01-01,2015-01-05,Standard Class,JS-1559559,Jill Stevenson,Corporate,NaN,Medan,Sumatera Utara,Indonesia,Southeastern Asia,Asia Pacific,TEC-CO-4588,"Hewlett Personal Copier, High-Speed",Copiers,Technology,264.9942,2,0.07,-17.1258,23.620,High
21971,29627,ID-2015-JS1559559-42005,2015-01-01,2015-01-05,Standard Class,JS-1559559,Jill Stevenson,Corporate,NaN,Medan,Sumatera Utara,Indonesia,Southeastern Asia,Asia Pacific,OFF-FA-6206,"Stockwell Thumb Tacks, Assorted Sizes",Fasteners,Office Supplies,17.4582,3,0.47,-9.2718,1.280,High
26277,9945,MX-2015-EN1378082-42005,2015-01-01,2015-01-05,Standard Class,EN-1378082,Edward Nazzal,Consumer,NaN,Milpa Alta,Distrito Federal,Mexico,Central America,LATAM,OFF-AR-3467,"BIC Pens, Water Color",Art,Office Supplies,46.5600,4,0.00,9.7600,6.992,High
26646,4345,MX-2015-PO1886582-42005,2015-01-01,2015-01-05,Standard Class,PO-1886582,Patrick O'Donnell,Consumer,NaN,Guadalajara,Jalisco,Mexico,Central America,LATAM,OFF-BI-2913,"Acco Hole Reinforcements, Durable",Binders,Office Supplies,27.2000,5,0.00,8.7000,2.140,Medium
35945,11361,ES-2015-VB21745120-42005,2015-01-01,2015-01-08,Standard Class,VB-21745120,Victoria Brennan,Corporate,NaN,Madrid,Madrid,Spain,Southern Europe,Europe,OFF-LA-4663,"Hon Legal Exhibit Labels, Adjustable",Labels,Office Supplies,61.3200,7,0.00,9.6600,2.430,Medium
36555,46028,TZ-2015-JE5610129-42005,2015-01-01,2015-01-06,Standard Class,JE-5610129,Jim Epp,Corporate,NaN,Arusha,Arusha,Tanzania,Eastern Africa,Africa,TEC-CO-3600,"Brother Ink, Digital",Copiers,Technology,293.8800,2,0.00,73.4400,18.390,Medium
37004,45916,TO-2015-PC8745131-42005,2015-01-01,2015-01-03,First Class,PC-8745131,Pamela Coakley,Corporate,NaN,Lome,Maritime,Togo,Western Africa,Africa,OFF-BI-2918,"Acco Index Tab, Durable",Binders,Office Supplies,71.5200,8,0.00,15.6000,14.650,Medium
43176,33783,CA-2015-CB12535140-42005,2015-01-01,2015-01-03,Second Class,CB-125351406,Claudia Bergmann,Corporate,19711.0,Newark,Delaware,United States,Eastern US,USCA,OFF-ST-5789,"SAFCO Mobile Desk Side File, Wire Frame",Storage,Office Supplies,85.5200,2,0.00,22.2352,15.810,Critical
43177,33785,CA-2015-CB12535140-42005,2015-01-01,2015-01-03,Second Class,CB-125351406,Claudia Bergmann,Corporate,19711.0,Newark,Delaware,United States,Eastern US,USCA,OFF-PA-6515,Xerox 1959,Paper,Office Supplies,20.0400,3,0.00,9.6192,4.750,Critical
43178,33784,CA-2015-CB12535140-42005,2015-01-01,2015-01-03,Second Class,CB-125351406,Claudia Bergmann,Corporate,19711.0,Newark,Delaware,United States,Eastern US,USCA,OFF-AR-5290,Newell 313,Art,Office Supplies,9.8400,3,0.00,2.6568,2.770,Critical
47445,31512,CA-2015-VW21775140-42005,2015-01-01,2015-01-08,Standard Class,VW-217751406,Victoria Wilson,Corporate,44256.0,Medina,Ohio,United States,Eastern US,USCA,TEC-MA-3783,Cisco 9971 IP Video Phone Charcoal,Machines,Technology,1188.0000,9,0.70,-950.4000,63.760,Medium
47446,31510,CA-2015-VW21775140-42005,2015-01-01,2015-01-08,Standard Class,VW-217751406,Victoria Wilson,Corporate,44256.0,Medina,Ohio,United States,Eastern US,USCA,FUR-BO-5519,O'Sullivan 2-Door Barrister Bookcase in Odessa...,Bookcases,Furniture,452.4500,5,0.50,-244.3230,34.270,Medium
47447,31511,CA-2015-VW21775140-42005,2015-01-01,2015-01-08,Standard Class,VW-217751406,Victoria Wilson,Corporate,44256.0,Medina,Ohio,United States,Eastern US,USCA,TEC-PH-6091,Speck Products Candyshell Flip Case,Phones,Technology,62.9820,3,0.40,-14.6958,6.260,Medium
47448,31513,CA-2015-VW21775140-42005,2015-01-01,2015-01-08,Standard Class,VW-217751406,Victoria Wilson,Corporate,44256.0,Medina,Ohio,United States,Eastern US,USCA,TEC-AC-6076,Sony Micro Vault Click 16 GB USB 2.0 Flash Drive,Accessories,Technology,89.5840,2,0.20,4.4792,4.960,Medium
47449,31509,CA-2015-VW21775140-42005,2015-01-01,2015-01-08,Standard Class,VW-217751406,Victoria Wilson,Corporate,44256.0,Medina,Ohio,United States,Eastern US,USCA,OFF-LA-3226,Avery 505,Labels,Office Supplies,23.6800,2,0.20,8.8800,1.390,Medium

In [30]:
df.loc[(df['Quantity']>=5) & (df['Profit']<0)]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,State,Country,Region,Market,Product ID,Product Name,Sub-Category,Category,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
390,6915,US-2017-BT115305-43067,2017-11-28,2017-12-03,Standard Class,BT-115305,Bradley Talbott,Home Office,NaN,Buenos Aires,Buenos Aires,Argentina,South America,LATAM,TEC-PH-5356,"Nokia Smart Phone, with Caller ID",Phones,Technology,1277.82000,5,0.400,-0.08000,129.153,Medium
391,6755,US-2017-BW112005-42919,2017-07-03,2017-07-05,Second Class,BW-112005,Ben Wallace,Consumer,NaN,Buenos Aires,Buenos Aires,Argentina,South America,LATAM,TEC-CO-6012,"Sharp Wireless Fax, Laser",Copiers,Technology,993.25408,7,0.402,-3.40592,109.642,High
392,6986,MX-2015-CR127305-42250,2015-09-03,2015-09-06,First Class,CR-127305,Craig Reiter,Consumer,NaN,Buenos Aires,Buenos Aires,Argentina,South America,LATAM,TEC-CO-3604,"Brother Personal Copier, Color",Copiers,Technology,345.23736,6,0.402,-24.36264,103.941,High
393,8221,MX-2015-JH159855-42283,2015-10-06,2015-10-07,Same Day,JH-159855,Joseph Holt,Consumer,NaN,Buenos Aires,Buenos Aires,Argentina,South America,LATAM,TEC-CO-3599,"Brother Ink, Color",Copiers,Technology,296.48840,5,0.402,-40.71160,100.933,High
396,9778,US-2017-PB191505-43091,2017-12-22,2017-12-29,Standard Class,PB-191505,Philip Brown,Consumer,NaN,Buenos Aires,Buenos Aires,Argentina,South America,LATAM,FUR-CH-4654,"Hon Executive Leather Armchair, Adjustable",Chairs,Furniture,919.26000,5,0.400,-168.54000,77.438,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51249,43445,ZA-2017-BT1395147-43067,2017-11-28,2017-11-30,Second Class,BT-1395147,Bill Tyler,Corporate,NaN,Chitungwiza,Harare,Zimbabwe,Eastern Africa,Africa,OFF-EN-4452,"GlobeWeis Peel and Seal, Security-Tint",Envelopes,Office Supplies,42.82200,6,0.700,-82.81800,6.380,Critical
51266,43911,ZA-2015-LC6885147-42021,2015-01-17,2015-01-17,Same Day,LC-6885147,Lena Creighton,Consumer,NaN,Harare,Harare,Zimbabwe,Eastern Africa,Africa,OFF-AR-5932,"Sanford Sketch Pad, Fluorescent",Art,Office Supplies,112.17600,8,0.700,-86.06400,26.840,High
51271,48018,ZA-2016-DB3210147-42472,2016-04-12,2016-04-15,First Class,DB-3210147,Dean Braden,Consumer,NaN,Harare,Harare,Zimbabwe,Eastern Africa,Africa,OFF-AR-5925,"Sanford Pens, Easy-Erase",Art,Office Supplies,20.46600,6,0.700,-32.09400,4.490,High
51272,50678,ZA-2017-EM3810147-43042,2017-11-03,2017-11-10,Standard Class,EM-3810147,Eleni McCrary,Corporate,NaN,Harare,Harare,Zimbabwe,Eastern Africa,Africa,OFF-BI-3720,"Cardinal Binder, Clear",Binders,Office Supplies,39.87000,10,0.700,-89.13000,4.220,Low
51275,41614,ZA-2015-SS10140147-42007,2015-01-03,2015-01-08,Standard Class,SS-10140147,Saphhira Shifley,Corporate,NaN,Harare,Harare,Zimbabwe,Eastern Africa,Africa,OFF-AR-3488,"Binney & Smith Markers, Blue",Art,Office Supplies,57.81600,8,0.700,-98.42400,2.140,Medium

In [34]:
df.sort_values(by = 'Sales',ascending = False).head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,State,Country,Region,Market,Product ID,Product Name,Sub-Category,Category,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
43417,33994,CA-2014-SM20320140-41715,2014-03-17,2014-03-22,Standard Class,SM-203201408,Sean Miller,Home Office,32216.0,Jacksonville,Florida,United States,Southern US,USCA,TEC-MA-3819,Cisco TelePresence System EX90 Videoconferenci...,Machines,Technology,22638.480,6,0.5,-1811.0784,24.28650,Medium
44434,38123,CA-2016-TC20980140-42646,2016-10-03,2016-10-10,Standard Class,TC-209801402,Tamara Chand,Corporate,47905.0,Lafayette,Indiana,United States,Central US,USCA,TEC-CO-3691,Canon imageCLASS 2200 Advanced Copier,Copiers,Technology,17499.950,5,0.0,8399.9760,349.07000,Medium
50323,39450,CA-2017-RB19360140-42818,2017-03-24,2017-03-26,First Class,RB-193601404,Raymond Buch,Consumer,98115.0,Seattle,Washington,United States,Western US,USCA,TEC-CO-3691,Canon imageCLASS 2200 Advanced Copier,Copiers,Technology,13999.960,4,0.0,6719.9808,20.00054,Medium
46710,33920,CA-2017-TA21385140-43031,2017-10-23,2017-10-25,First Class,TA-213851406,Tom Ashbrook,Home Office,10024.0,New York City,New York,United States,Eastern US,USCA,TEC-CO-3691,Canon imageCLASS 2200 Advanced Copier,Copiers,Technology,11199.968,4,0.2,3919.9888,45.98000,High
43198,35487,CA-2017-HL15040140-43057,2017-11-18,2017-11-23,Standard Class,HL-150401406,Hunter Lopez,Consumer,19711.0,Newark,Delaware,United States,Eastern US,USCA,TEC-CO-3691,Canon imageCLASS 2200 Advanced Copier,Copiers,Technology,10499.970,3,0.0,5039.9856,363.19000,Medium
45000,40336,CA-2016-AB10105140-42722,2016-12-18,2016-12-22,Standard Class,AB-101051402,Adrian Barton,Consumer,48205.0,Detroit,Michigan,United States,Central US,USCA,OFF-BI-4345,GBC Ibimaster 500 Manual ProClick Binding System,Binders,Office Supplies,9892.740,13,0.0,4946.3700,498.70000,Medium
45288,35395,CA-2014-SC20095140-41904,2014-09-22,2014-09-27,Standard Class,SC-200951402,Sanjit Chand,Consumer,55407.0,Minneapolis,Minnesota,United States,Central US,USCA,OFF-BI-4821,Ibico EPK-21 Electric Binding System,Binders,Office Supplies,9449.950,5,0.0,4630.4755,655.61000,Medium
45592,35574,US-2016-BS11365140-42477,2016-04-17,2016-04-21,Standard Class,BS-113651406,Bill Shonely,Corporate,8701.0,Lakewood,New Jersey,United States,Eastern US,USCA,TEC-MA-2865,"3D Systems Cube Printer, 2nd Generation, Magenta",Machines,Technology,9099.930,7,0.0,2365.9818,516.91000,Medium
49744,39785,CA-2016-SE20110140-42402,2016-02-02,2016-02-04,Second Class,SE-201101408,Sanjit Engle,Consumer,22204.0,Arlington,Virginia,United States,Southern US,USCA,TEC-MA-4768,HP Designjet T520 Inkjet Large Format Printer ...,Machines,Technology,8749.950,5,0.0,2799.9840,17.83000,Critical
47916,37722,CA-2016-CC12370140-42514,2016-05-24,2016-05-28,Standard Class,CC-123701406,Christopher Conant,Consumer,19120.0,Philadelphia,Pennsylvania,United States,Eastern US,USCA,TEC-CO-3691,Canon imageCLASS 2200 Advanced Copier,Copiers,Technology,8399.976,4,0.4,1119.9968,498.08000,Medium

In [36]:
df.sort_values(by = 'Profit').head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,State,Country,Region,Market,Product ID,Product Name,Sub-Category,Category,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
47386,39069,CA-2016-CS12505140-42700,2016-11-26,2016-12-03,Standard Class,CS-125051406,Cindy Stewart,Consumer,43130.0,Lancaster,Ohio,United States,Eastern US,USCA,TEC-MA-3854,Cubify CubeX 3D Printer Double Head Print,Machines,Technology,4499.985,5,0.7,-6599.9780,451.63,Low
38044,48663,TU-2016-DM3345134-42639,2016-09-26,2016-09-26,Same Day,DM-3345134,Denise Monton,Corporate,NaN,Bornova,Izmir,Turkey,Western Asia,Asia Pacific,TEC-PH-5267,"Motorola Smart Phone, Cordless",Phones,Technology,3085.344,12,0.6,-4088.3760,51.89,Critical
46865,31980,US-2017-GT14635140-43044,2017-11-05,2017-11-05,Same Day,GT-146351408,Grant Thornton,Corporate,27217.0,Burlington,North Carolina,United States,Southern US,USCA,TEC-MA-3855,Cubify CubeX 3D Printer Triple Head Print,Machines,Technology,7999.980,4,0.5,-3839.9904,674.82,High
49593,41071,CA-2014-LF17185140-41845,2014-07-25,2014-07-29,Standard Class,LF-171851402,Luke Foster,Consumer,78207.0,San Antonio,Texas,United States,Central US,USCA,OFF-BI-4340,GBC DocuBind P400 Electric Binding System,Binders,Office Supplies,2177.584,8,0.8,-3701.8928,172.07,Medium
43040,34308,CA-2017-SR20425140-42843,2017-04-18,2017-04-24,Standard Class,SR-204251404,Sharelle Roach,Home Office,80027.0,Louisville,Colorado,United States,Western US,USCA,TEC-MA-5082,Lexmark MX611dhe Monochrome Laser Printer,Machines,Technology,2549.985,5,0.7,-3399.9800,120.31,Medium
33287,10458,IT-2016-SS20140104-42531,2016-06-10,2016-06-14,Standard Class,SS-20140104,Saphhira Shifley,Corporate,NaN,Lisbon,Lisboa,Portugal,Southern Europe,Europe,OFF-AP-4745,"Hoover Stove, White",Appliances,Office Supplies,3399.660,12,0.5,-3059.8200,286.87,Medium
31563,29513,ID-2016-SN2056097-42627,2016-09-14,2016-09-14,Same Day,SN-2056097,Skye Norling,Home Office,NaN,Lahore,Punjab,Pakistan,Southern Asia,Asia Pacific,TEC-PH-3148,"Apple Smart Phone, Full Size",Phones,Technology,3499.155,11,0.5,-3009.4350,333.10,Medium
44030,36288,US-2017-HG14965140-43077,2017-12-08,2017-12-14,Standard Class,HG-149651402,Henry Goldwyn,Corporate,60653.0,Chicago,Illinois,United States,Central US,USCA,OFF-BI-4821,Ibico EPK-21 Electric Binding System,Binders,Office Supplies,1889.990,5,0.8,-2929.4845,129.51,Medium
25043,46219,LH-2017-JC610575-42763,2017-01-28,2017-01-30,Second Class,JC-610575,Julie Creighton,Corporate,NaN,Vilnius,Vilnius,Lithuania,Northern Europe,Europe,FUR-TA-3345,"Barricks Conference Table, Rectangular",Tables,Furniture,2171.160,8,0.7,-2750.2800,390.09,High
47482,34448,CA-2015-NF18385140-42353,2015-12-15,2015-12-18,First Class,NF-183851406,Natalie Fritzler,Consumer,43055.0,Newark,Ohio,United States,Eastern US,USCA,TEC-MA-3854,Cubify CubeX 3D Printer Double Head Print,Machines,Technology,1799.994,2,0.7,-2639.9912,219.62,High

In [38]:
df = df.sort_values(by = 'Sales', ascending = False)
df

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,State,Country,Region,Market,Product ID,Product Name,Sub-Category,Category,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
43417,33994,CA-2014-SM20320140-41715,2014-03-17,2014-03-22,Standard Class,SM-203201408,Sean Miller,Home Office,32216.0,Jacksonville,Florida,United States,Southern US,USCA,TEC-MA-3819,Cisco TelePresence System EX90 Videoconferenci...,Machines,Technology,22638.480,6,0.5,-1811.0784,24.28650,Medium
44434,38123,CA-2016-TC20980140-42646,2016-10-03,2016-10-10,Standard Class,TC-209801402,Tamara Chand,Corporate,47905.0,Lafayette,Indiana,United States,Central US,USCA,TEC-CO-3691,Canon imageCLASS 2200 Advanced Copier,Copiers,Technology,17499.950,5,0.0,8399.9760,349.07000,Medium
50323,39450,CA-2017-RB19360140-42818,2017-03-24,2017-03-26,First Class,RB-193601404,Raymond Buch,Consumer,98115.0,Seattle,Washington,United States,Western US,USCA,TEC-CO-3691,Canon imageCLASS 2200 Advanced Copier,Copiers,Technology,13999.960,4,0.0,6719.9808,20.00054,Medium
46710,33920,CA-2017-TA21385140-43031,2017-10-23,2017-10-25,First Class,TA-213851406,Tom Ashbrook,Home Office,10024.0,New York City,New York,United States,Eastern US,USCA,TEC-CO-3691,Canon imageCLASS 2200 Advanced Copier,Copiers,Technology,11199.968,4,0.2,3919.9888,45.98000,High
43198,35487,CA-2017-HL15040140-43057,2017-11-18,2017-11-23,Standard Class,HL-150401406,Hunter Lopez,Consumer,19711.0,Newark,Delaware,United States,Eastern US,USCA,TEC-CO-3691,Canon imageCLASS 2200 Advanced Copier,Copiers,Technology,10499.970,3,0.0,5039.9856,363.19000,Medium
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
49490,33403,US-2014-HG14965140-41907,2014-09-25,2014-09-25,Same Day,HG-149651402,Henry Goldwyn,Corporate,75150.0,Mesquite,Texas,United States,Central US,USCA,OFF-BI-2880,Acco 3-Hole Punch,Binders,Office Supplies,0.876,1,0.8,-1.4016,1.09000,High
48048,36008,CA-2014-JO15280140-41728,2014-03-30,2014-03-30,Same Day,JO-152801406,Jas O'Carroll,Consumer,19120.0,Philadelphia,Pennsylvania,United States,Eastern US,USCA,OFF-BI-3318,Avery Round Ring Poly Binders,Binders,Office Supplies,0.852,1,0.7,-0.5964,1.10000,High
44065,39955,CA-2016-KB16600140-42543,2016-06-22,2016-06-26,Standard Class,KB-166001402,Ken Brennan,Corporate,60623.0,Chicago,Illinois,United States,Central US,USCA,OFF-BI-3268,Avery Durable Slant Ring Binders With Label Ho...,Binders,Office Supplies,0.836,1,0.8,-1.3376,1.06000,Medium
49636,40589,CA-2017-RS19765140-42797,2017-03-03,2017-03-03,Same Day,RS-197651402,Roland Schwarz,Corporate,76706.0,Waco,Texas,United States,Central US,USCA,OFF-BI-2935,Acco Suede Grain Vinyl Round Ring Binder,Binders,Office Supplies,0.556,1,0.8,-0.9452,1.08000,Medium
49405,35398,US-2017-ZC21910140-42906,2017-06-20,2017-06-24,Standard Class,ZC-219101402,Zuschuss Carroll,Consumer,77095.0,Houston,Texas,United States,Central US,USCA,OFF-AP-4739,Hoover Replacement Belt for Commercial Guardsm...,Appliances,Office Supplies,0.444,1,0.8,-1.1100,1.01000,Medium

In [40]:
df.sort_values(by = 'Profit',ascending = False).head(10)

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,State,Country,Region,Market,Product ID,Product Name,Sub-Category,Category,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
44434,38123,CA-2016-TC20980140-42646,2016-10-03,2016-10-10,Standard Class,TC-209801402,Tamara Chand,Corporate,47905.0,Lafayette,Indiana,United States,Central US,USCA,TEC-CO-3691,Canon imageCLASS 2200 Advanced Copier,Copiers,Technology,17499.950,5,0.0,8399.9760,349.07000,Medium
50323,39450,CA-2017-RB19360140-42818,2017-03-24,2017-03-26,First Class,RB-193601404,Raymond Buch,Consumer,98115.0,Seattle,Washington,United States,Western US,USCA,TEC-CO-3691,Canon imageCLASS 2200 Advanced Copier,Copiers,Technology,13999.960,4,0.0,6719.9808,20.00054,Medium
43198,35487,CA-2017-HL15040140-43057,2017-11-18,2017-11-23,Standard Class,HL-150401406,Hunter Lopez,Consumer,19711.0,Newark,Delaware,United States,Eastern US,USCA,TEC-CO-3691,Canon imageCLASS 2200 Advanced Copier,Copiers,Technology,10499.970,3,0.0,5039.9856,363.19000,Medium
45000,40336,CA-2016-AB10105140-42722,2016-12-18,2016-12-22,Standard Class,AB-101051402,Adrian Barton,Consumer,48205.0,Detroit,Michigan,United States,Central US,USCA,OFF-BI-4345,GBC Ibimaster 500 Manual ProClick Binding System,Binders,Office Supplies,9892.740,13,0.0,4946.3700,498.70000,Medium
45288,35395,CA-2014-SC20095140-41904,2014-09-22,2014-09-27,Standard Class,SC-200951402,Sanjit Chand,Consumer,55407.0,Minneapolis,Minnesota,United States,Central US,USCA,OFF-BI-4821,Ibico EPK-21 Electric Binding System,Binders,Office Supplies,9449.950,5,0.0,4630.4755,655.61000,Medium
24294,12069,ES-2017-PJ1883564-42986,2017-09-08,2017-09-14,Standard Class,PJ-1883564,Patrick Jones,Corporate,NaN,Prato,Tuscany,Italy,Southern Europe,Europe,OFF-AP-4743,"Hoover Stove, Red",Appliances,Office Supplies,7958.580,14,0.0,3979.0800,778.32000,Low
46710,33920,CA-2017-TA21385140-43031,2017-10-23,2017-10-25,First Class,TA-213851406,Tom Ashbrook,Home Office,10024.0,New York City,New York,United States,Eastern US,USCA,TEC-CO-3691,Canon imageCLASS 2200 Advanced Copier,Copiers,Technology,11199.968,4,0.2,3919.9888,45.98000,High
43666,31806,CA-2015-CM12385140-42079,2015-03-16,2015-03-22,Standard Class,CM-123851408,Christopher Martinez,Consumer,30318.0,Atlanta,Georgia,United States,Southern US,USCA,OFF-BI-4276,Fellowes PB500 Electric Punch Plastic Comb Bin...,Binders,Office Supplies,6354.950,5,0.0,3177.4750,581.12000,Medium
24582,27720,ID-2014-CA1196566-41680,2014-02-10,2014-02-15,Standard Class,CA-1196566,Carol Adams,Corporate,NaN,Fuji,Shizuoka,Japan,Eastern Asia,Asia Pacific,TEC-PH-5841,"Samsung Smart Phone, VoIP",Phones,Technology,6998.640,11,0.0,2939.3100,413.80000,Medium
19301,23212,IN-2016-CA1277558-42533,2016-06-12,2016-06-17,Standard Class,CA-1277558,Cynthia Arntzen,Consumer,NaN,Kota,Chhattisgarh,India,Southern Asia,Asia Pacific,TEC-PH-3149,"Apple Smart Phone, with Caller ID",Phones,Technology,5751.540,9,0.0,2817.9900,353.85000,Medium

In [69]:
df.isna().sum()

Number        0
Name          0
Type 1        0
Type 2       57
Abilities     0
HP            0
Att           0
Def           0
Legendary     0
Height        0
Weight        0
BMI           0
dtype: int64

# **GroupBy**

In [62]:
df.groupby('Segment').count()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Postal Code,City,State,Country,Region,Market,Product ID,Product Name,Sub-Category,Category,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
Segment,,,,,,,,,,,,,,,,,,,,,,,
Consumer,26518,26518,26518,26518,26518,26518,26518,5191,26518,26518,26518,26518,26518,26518,26518,26518,26518,26518,26518,26518,26518,26518,26518
Corporate,15429,15429,15429,15429,15429,15429,15429,3020,15429,15429,15429,15429,15429,15429,15429,15429,15429,15429,15429,15429,15429,15429,15429
Home Office,9343,9343,9343,9343,9343,9343,9343,1783,9343,9343,9343,9343,9343,9343,9343,9343,9343,9343,9343,9343,9343,9343,9343

In [65]:
df.groupby('Segment').max()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Postal Code,City,State,Country,Region,Market,Product ID,Product Name,Sub-Category,Category,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority
Segment,,,,,,,,,,,,,,,,,,,,,,,
Consumer,51289,ZA-2017-SM10005146-42972,2017-12-31,2018-01-06,Standard Class,ZD-2192596,Zuschuss Donatelli,99301.0,Águas Lindas de Goiás,Žilina,Zimbabwe,Western US,USCA,TEC-PH-6427,netTALK DUO VoIP Telephone Service,Tables,Technology,13999.96,14,0.80,6719.9808,933.57,Medium
Corporate,51281,ZA-2017-TS11205146-42793,2017-12-31,2018-01-07,Standard Class,YS-2188093,Yoseph Carroll,99207.0,eMbalenhle,Zürich,Zimbabwe,Western US,USCA,TEC-PH-6425,netTALK DUO VoIP Telephone Service,Tables,Technology,17499.95,14,0.85,8399.9760,923.63,Medium
Home Office,51290,ZA-2017-SW10350146-42792,2017-12-31,2018-01-06,Standard Class,VT-2170097,Victor Preis,99207.0,Águas Lindas de Goiás,Zürich,Zimbabwe,Western US,USCA,TEC-PH-6626,netTALK DUO VoIP Telephone Service,Tables,Technology,22638.48,14,0.85,3919.9888,910.16,Medium

In [70]:
df.groupby('Sales').agg({'Quantity':['sum','min','max'],'Ship Mode':['sum','min','max']})

          Quantity               Ship Mode
               sum min max             sum             min             max
Sales
0.444            1   1   1  Standard Class  Standard Class  Standard Class
0.556            1   1   1        Same Day        Same Day        Same Day
0.836            1   1   1  Standard Class  Standard Class  Standard Class
0.852            1   1   1        Same Day        Same Day        Same Day
0.876            1   1   1        Same Day        Same Day        Same Day
...            ...  ..  ..             ...             ...             ...
10499.970        3   3   3  Standard Class  Standard Class  Standard Class
11199.968        4   4   4     First Class     First Class     First Class
13999.960        4   4   4     First Class     First Class     First Class
17499.950        5   5   5  Standard Class  Standard Class  Standard Class
22638.480        6   6   6  Standard Class  Standard Class  Standard Class

[22995 rows x 6 columns]

In [72]:
df.groupby(['Sales','Profit']).agg({'Quantity':['sum','min','max']})

                     Quantity
                          sum min max
Sales     Profit
0.444     -1.1100           1   1   1
0.556     -0.9452           1   1   1
0.836     -1.3376           1   1   1
0.852     -0.5964           1   1   1
0.876     -1.4016           1   1   1
...                       ...  ..  ..
10499.970  5039.9856        3   3   3
11199.968  3919.9888        4   4   4
13999.960  6719.9808        4   4   4
17499.950  8399.9760        5   5   5
22638.480 -1811.0784        6   6   6

[38450 rows x 3 columns]

In [ ]:
df['Profit'].describe()

In [13]:
total_op = df.groupby('Category')
total_op['Sales'].sum()

Category
Furniture          4.110452e+06
Office Supplies    3.787493e+06
Technology         4.744557e+06
Name: Sales, dtype: float64

In [14]:
total_op['Profit'].sum()

Category
Furniture          285082.73020
Office Supplies    518595.82790
Technology         663778.73318
Name: Profit, dtype: float64

In [15]:
total_op['Sales'].mean()

Category
Furniture          416.881531
Office Supplies    121.048692
Technology         467.858939
Name: Sales, dtype: float64

In [16]:
total_op['Quantity'].count()

Category
Furniture           9860
Office Supplies    31289
Technology         10141
Name: Quantity, dtype: int64

In [26]:
total_sales = df.groupby('Country')
total_sales['Sales'].sum().sort_values(ascending = False).head(10)

Country
United States     2.297201e+06
Australia         9.252359e+05
France            8.589311e+05
China             7.005620e+05
Germany           6.281362e+05
Mexico            6.215526e+05
India             5.894860e+05
United Kingdom    5.285763e+05
Indonesia         4.048875e+05
Brazil            3.599249e+05
Name: Sales, dtype: float64

In [49]:
category_op = df.groupby('Category')
category_op[['Sales','Profit','Quantity']].agg({'Sales':['sum','mean'],
                                                'Profit':['sum','mean'],
                                               'Quantity':['sum','mean']})

                        Sales                    Profit            Quantity  \
                          sum        mean           sum       mean      sum
Category
Furniture        4.110452e+06  416.881531  285082.73020  28.913056    34892
Office Supplies  3.787493e+06  121.048692  518595.82790  16.574382   108244
Technology       4.744557e+06  467.858939  663778.73318  65.454958    35176


                     mean
Category
Furniture        3.538742
Office Supplies  3.459491
Technology       3.468691

In [39]:
category_op['Quantity'].agg()

                    sum      mean
Category
Furniture         34892  3.538742
Office Supplies  108244  3.459491
Technology        35176  3.468691

In [47]:
region_op = df.groupby('Region')
region_op[['Sales','Profit']].agg({'Sales':['sum']
                                   ,'Profit':['sum','mean']})

                          Sales        Profit
                            sum           sum       mean
Region
Canada             6.692817e+04   17817.39000  46.399453
Caribbean          3.242809e+05   34571.32104  20.456403
Central Africa     1.436300e+05   35383.71000  55.029098
Central America    1.223101e+06  158981.64816  28.308698
Central Asia       1.931146e+04   -7282.01100 -33.557654
Central US         5.012399e+05   39706.36250  17.092709
Eastern Africa     1.278560e+05   21900.90900  30.083666
Eastern Asia       8.550594e+05  167101.85100  70.388311
Eastern Europe     3.100334e+05   77084.88000  50.415226
Eastern US         6.787812e+05   91522.78000  32.135808
North Africa       2.332166e+05   57836.25000  45.255282
Northern Europe    6.367792e+05   83923.91700  38.078002
Oceania            1.100185e+06  120089.11200  34.439091
South America      6.172237e+05   28090.51788   9.401110
Southeastern Asia  8.844232e+05   17852.32900   5.705442
Southern Africa    1.051918e+05   24158.55000  50.540900
Southern Asia      8.665727e+05  159336.42700  60.013720
Southern Europe    6.085940e+05   70109.41800  33.180037
Southern US        3.917219e+05   46749.43030  28.857673
Western Africa     1.738788e+05  -50407.78800 -34.525882
Western Asia       3.171070e+05  -53921.67000 -22.099045
Western Europe     1.731930e+06  218433.50850  37.129612
Western US         7.254578e+05  108418.44890  33.849032

In [50]:
df.columns

Index(['Row ID', 'Order ID', 'Order Date', 'Ship Date', 'Ship Mode',
       'Customer ID', 'Customer Name', 'Segment', 'Postal Code', 'City',
       'State', 'Country', 'Region', 'Market', 'Product ID', 'Product Name',
       'Sub-Category', 'Category', 'Sales', 'Quantity', 'Discount', 'Profit',
       'Shipping Cost', 'Order Priority'],
      dtype='object')

In [54]:
# for segment - total sales,profit and avg sales,profit
# for category + subcate combo calculate sales and profit
combined_category = df.groupby(['Category','Sub-Category'])
combined_category[['Sales','Profit']].agg('sum')

                                     Sales        Profit
Category        Sub-Category
Furniture       Bookcases     1.466572e+06  161924.41950
                Chairs        1.501682e+06  140396.26750
                Furnishings   3.851560e+05   46845.43190
                Tables        7.570419e+05  -64083.38870
Office Supplies Appliances    1.010536e+06  141562.58770
                Art           3.716132e+05   57829.85930
                Binders       4.618694e+05   72433.15160
                Envelopes     1.692175e+05   28849.48730
                Fasteners     8.949505e+04   13844.28890
                Labels        7.335028e+04   14988.92370
                Paper         2.417875e+05   58111.65350
                Storage       1.126813e+06  108416.68060
                Supplies      2.428111e+05   22559.19530
Technology      Accessories   7.492370e+05  129626.30620
                Copiers       1.509436e+06  258567.54818
                Machines      7.790601e+05   58867.87300
                Phones        1.706824e+06  216717.00580

In [6]:
total_seg = df.groupby('Segment')
total_seg[['Sales','Profit']].agg({'Sales':'mean',
                                  'Profit':'mean'})

                  Sales     Profit
Segment
Consumer     245.416299  28.254008
Corporate    247.890176  28.596042
Home Office  247.228403  29.648847

# *Date and time*

In [4]:
df.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Postal Code              float64
City                      object
State                     object
Country                   object
Region                    object
Market                    object
Product ID                object
Product Name              object
Sub-Category              object
Category                  object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
Shipping Cost            float64
Order Priority            object
dtype: object

In [5]:
from datetime import datetime

In [7]:
now = datetime.now()
print(now)

2026-08-22 15:34:31.787033

In [12]:
date = datetime(1998,3,21)
date = datetime(1998,3,21,23,13,53)
print(date.year)
print(date.month)
print(date.day)
print(date.second)

1998
3
21
53

In [21]:
df['Order Date'] = df['Order Date'].astype(int)
df.dtypes

Row ID                     int64
Order ID                  object
Order Date                 int64
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Postal Code              float64
City                      object
State                     object
Country                   object
Region                    object
Market                    object
Product ID                object
Product Name              object
Sub-Category              object
Category                  object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
Shipping Cost            float64
Order Priority            object
dtype: object

In [23]:
df['Order Date'] = pd.to_datetime(df['Order Date'])
# converts date into actual datetime data type

In [24]:
df.dtypes

Row ID                     int64
Order ID                  object
Order Date        datetime64[ns]
Ship Date         datetime64[ns]
Ship Mode                 object
Customer ID               object
Customer Name             object
Segment                   object
Postal Code              float64
City                      object
State                     object
Country                   object
Region                    object
Market                    object
Product ID                object
Product Name              object
Sub-Category              object
Category                  object
Sales                    float64
Quantity                   int64
Discount                 float64
Profit                   float64
Shipping Cost            float64
Order Priority            object
dtype: object

In [27]:
df['Order Date'].dt.year
df['Order Date'].dt.month
df['Order Date'].dt.day

0        2
1        1
2        2
3        2
4        1
        ..
51285    3
51286    6
51287    0
51288    3
51289    6
Name: Order Date, Length: 51290, dtype: int32

In [37]:
df['Year'] = df['Order Date'].dt.year

In [40]:
df['Month Name'] = df['Order Date'].dt.month_name()

In [41]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,State,Country,Region,Market,Product ID,Product Name,Sub-Category,Category,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Year,Month Name
0,24599,IN-2017-CA120551-42816,2017-03-22,2017-03-29,Standard Class,CA-120551,Cathy Armstrong,Home Office,NaN,Herat,Hirat,Afghanistan,Southern Asia,Asia Pacific,FUR-BO-4861,"Ikea Library with Doors, Mobile",Bookcases,Furniture,731.82,2,0.0,102.42,39.66,Medium,2017,March
1,29465,ID-2015-BD116051-42248,2015-09-01,2015-09-04,Second Class,BD-116051,Brian Dahlen,Consumer,NaN,Herat,Hirat,Afghanistan,Southern Asia,Asia Pacific,OFF-SU-2988,"Acme Scissors, Easy Grip",Supplies,Office Supplies,243.54,9,0.0,104.49,18.72,Medium,2015,September
2,24598,IN-2017-CA120551-42816,2017-03-22,2017-03-29,Standard Class,CA-120551,Cathy Armstrong,Home Office,NaN,Herat,Hirat,Afghanistan,Southern Asia,Asia Pacific,TEC-MA-4211,"Epson Receipt Printer, White",Machines,Technology,346.32,3,0.0,13.77,14.10,Medium,2017,March
3,24597,IN-2017-CA120551-42816,2017-03-22,2017-03-29,Standard Class,CA-120551,Cathy Armstrong,Home Office,NaN,Herat,Hirat,Afghanistan,Southern Asia,Asia Pacific,FUR-FU-5726,"Rubbermaid Door Stop, Erganomic",Furnishings,Furniture,169.68,4,0.0,79.68,11.01,Medium,2017,March
4,29464,ID-2015-BD116051-42248,2015-09-01,2015-09-04,Second Class,BD-116051,Brian Dahlen,Consumer,NaN,Herat,Hirat,Afghanistan,Southern Asia,Asia Pacific,OFF-EN-3664,"Cameo Interoffice Envelope, with clear poly wi...",Envelopes,Office Supplies,203.88,4,0.0,24.36,5.72,Medium,2015,September

In [43]:
df[df['Year'] == 2015]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,State,Country,Region,Market,Product ID,Product Name,Sub-Category,Category,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Year,Month Name
1,29465,ID-2015-BD116051-42248,2015-09-01,2015-09-04,Second Class,BD-116051,Brian Dahlen,Consumer,NaN,Herat,Hirat,Afghanistan,Southern Asia,Asia Pacific,OFF-SU-2988,"Acme Scissors, Easy Grip",Supplies,Office Supplies,243.540,9,0.0,104.490,18.72,Medium,2015,September
4,29464,ID-2015-BD116051-42248,2015-09-01,2015-09-04,Second Class,BD-116051,Brian Dahlen,Consumer,NaN,Herat,Hirat,Afghanistan,Southern Asia,Asia Pacific,OFF-EN-3664,"Cameo Interoffice Envelope, with clear poly wi...",Envelopes,Office Supplies,203.880,4,0.0,24.360,5.72,Medium,2015,September
5,28879,ID-2015-AJ107801-42113,2015-04-19,2015-04-22,First Class,AJ-107801,Anthony Jacobs,Corporate,NaN,Kabul,Kabul,Afghanistan,Southern Asia,Asia Pacific,FUR-TA-3420,"Bevis Conference Table, Fully Assembled",Tables,Furniture,4626.150,5,0.0,647.550,835.57,High,2015,April
10,25232,ID-2015-SS201401-42354,2015-12-16,2015-12-20,Standard Class,SS-201401,Saphhira Shifley,Corporate,NaN,Kabul,Kabul,Afghanistan,Southern Asia,Asia Pacific,FUR-TA-3780,"Chromcraft Wood Table, with Bottom Storage",Tables,Furniture,1447.560,3,0.0,564.480,73.63,Medium,2015,December
12,29094,IN-2015-BG110351-42275,2015-09-28,2015-10-04,Standard Class,BG-110351,Barry Gonzalez,Consumer,NaN,Kabul,Kabul,Afghanistan,Southern Asia,Asia Pacific,TEC-CO-4588,"Hewlett Personal Copier, High-Speed",Copiers,Technology,427.410,3,0.0,4.230,60.91,Low,2015,September
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51270,44670,ZA-2015-ON8715147-42100,2015-04-06,2015-04-09,First Class,ON-8715147,Odella Nelson,Corporate,NaN,Harare,Harare,Zimbabwe,Eastern Africa,Africa,OFF-AR-3501,"Binney & Smith Sketch Pad, Fluorescent",Art,Office Supplies,57.096,4,0.7,-123.744,11.45,High,2015,April
51274,43908,ZA-2015-LC6885147-42021,2015-01-17,2015-01-17,Same Day,LC-6885147,Lena Creighton,Consumer,NaN,Harare,Harare,Zimbabwe,Eastern Africa,Africa,OFF-SU-4304,"Fiskars Box Cutter, High Speed",Supplies,Office Supplies,10.656,1,0.7,-12.444,2.89,High,2015,January
51275,41614,ZA-2015-SS10140147-42007,2015-01-03,2015-01-08,Standard Class,SS-10140147,Saphhira Shifley,Corporate,NaN,Harare,Harare,Zimbabwe,Eastern Africa,Africa,OFF-AR-3488,"Binney & Smith Markers, Blue",Art,Office Supplies,57.816,8,0.7,-98.424,2.14,Medium,2015,January
51282,42683,ZA-2015-AB10060147-42239,2015-08-23,2015-08-24,First Class,AB-10060147,Adam Bellavance,Home Office,NaN,Harare,Harare,Zimbabwe,Eastern Africa,Africa,OFF-BI-3249,"Avery Binder Covers, Recycled",Binders,Office Supplies,6.858,2,0.7,-7.782,1.16,Medium,2015,August
51288,47164,ZA-2015-JG5115147-42040,2015-02-05,2015-02-10,Standard Class,JG-5115147,Jack Garza,Consumer,NaN,Kadoma,Mashonaland West,Zimbabwe,Eastern Africa,Africa,TEC-MA-5542,"Panasonic Card Printer, Durable",Machines,Technology,104.364,2,0.7,-173.976,7.46,Medium,2015,February

In [45]:
df[df['Order Date'].dt.month>=7]

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,State,Country,Region,Market,Product ID,Product Name,Sub-Category,Category,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Year,Month Name
1,29465,ID-2015-BD116051-42248,2015-09-01,2015-09-04,Second Class,BD-116051,Brian Dahlen,Consumer,NaN,Herat,Hirat,Afghanistan,Southern Asia,Asia Pacific,OFF-SU-2988,"Acme Scissors, Easy Grip",Supplies,Office Supplies,243.540,9,0.0,104.490,18.72,Medium,2015,September
4,29464,ID-2015-BD116051-42248,2015-09-01,2015-09-04,Second Class,BD-116051,Brian Dahlen,Consumer,NaN,Herat,Hirat,Afghanistan,Southern Asia,Asia Pacific,OFF-EN-3664,"Cameo Interoffice Envelope, with clear poly wi...",Envelopes,Office Supplies,203.880,4,0.0,24.360,5.72,Medium,2015,September
6,27993,IN-2017-GM144551-42948,2017-08-01,2017-08-05,Standard Class,GM-144551,Gary Mitchum,Home Office,NaN,Kabul,Kabul,Afghanistan,Southern Asia,Asia Pacific,FUR-BO-3626,"Bush Classic Bookcase, Pine",Bookcases,Furniture,2070.150,5,0.0,848.700,185.01,Medium,2017,August
7,28967,IN-2017-VB217451-43080,2017-12-11,2017-12-15,Standard Class,VB-217451,Victoria Brennan,Corporate,NaN,Kabul,Kabul,Afghanistan,Southern Asia,Asia Pacific,FUR-CH-4683,"Hon Rocking Chair, Red",Chairs,Furniture,914.340,7,0.0,356.580,106.41,High,2017,December
8,29492,IN-2016-LO171701-42637,2016-09-24,2016-09-28,Standard Class,LO-171701,Lori Olson,Corporate,NaN,Kabul,Kabul,Afghanistan,Southern Asia,Asia Pacific,TEC-PH-5814,"Samsung Audio Dock, VoIP",Phones,Technology,1168.440,7,0.0,443.940,92.34,Medium,2016,September
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
51273,42718,ZA-2017-GR4560147-42947,2017-07-31,2017-08-01,First Class,GR-4560147,Georgia Rosenberg,Corporate,NaN,Harare,Harare,Zimbabwe,Eastern Africa,Africa,FUR-BO-4859,"Ikea Floating Shelf Set, Traditional",Bookcases,Furniture,51.102,1,0.7,-109.038,3.26,Critical,2017,July
51276,48014,ZA-2017-NG8430147-43063,2017-11-24,2017-11-30,Standard Class,NG-8430147,Nathan Gelder,Consumer,NaN,Harare,Harare,Zimbabwe,Eastern Africa,Africa,TEC-MA-5494,"Okidata Calculator, Red",Machines,Technology,14.832,1,0.7,-20.298,1.93,Medium,2017,November
51279,48013,ZA-2017-NG8430147-43063,2017-11-24,2017-11-30,Standard Class,NG-8430147,Nathan Gelder,Consumer,NaN,Harare,Harare,Zimbabwe,Eastern Africa,Africa,OFF-AR-5923,"Sanford Pencil Sharpener, Water Color",Art,Office Supplies,7.830,1,0.7,-11.490,1.61,Medium,2017,November
51282,42683,ZA-2015-AB10060147-42239,2015-08-23,2015-08-24,First Class,AB-10060147,Adam Bellavance,Home Office,NaN,Harare,Harare,Zimbabwe,Eastern Africa,Africa,OFF-BI-3249,"Avery Binder Covers, Recycled",Binders,Office Supplies,6.858,2,0.7,-7.782,1.16,Medium,2015,August
51284,48012,ZA-2017-NG8430147-43063,2017-11-24,2017-11-30,Standard Class,NG-8430147,Nathan Gelder,Consumer,NaN,Harare,Harare,Zimbabwe,Eastern Africa,Africa,OFF-BI-6397,"Wilson Jones Hole Reinforcements, Clear",Binders,Office Supplies,1.197,1,0.7,-2.373,1.06,Medium,2017,November

In [50]:
date1 = pd.to_datetime("2015-4-12")
date2 = pd.to_datetime("2015-4-18")
date1 > date2

False

In [51]:
date1 < date2

True

In [52]:
df['Shipping Days'] = df['Ship Date'] - df['Order Date']

In [56]:
df['Shipping Days'].dt.days

0        7
1        3
2        7
3        7
4        3
        ..
51285    5
51286    2
51287    6
51288    5
51289    5
Name: Shipping Days, Length: 51290, dtype: int64

In [53]:
df.head()

,Row ID,Order ID,Order Date,Ship Date,Ship Mode,Customer ID,Customer Name,Segment,Postal Code,City,State,Country,Region,Market,Product ID,Product Name,Sub-Category,Category,Sales,Quantity,Discount,Profit,Shipping Cost,Order Priority,Year,Month Name,Shipping Days
0,24599,IN-2017-CA120551-42816,2017-03-22,2017-03-29,Standard Class,CA-120551,Cathy Armstrong,Home Office,NaN,Herat,Hirat,Afghanistan,Southern Asia,Asia Pacific,FUR-BO-4861,"Ikea Library with Doors, Mobile",Bookcases,Furniture,731.82,2,0.0,102.42,39.66,Medium,2017,March,7 days
1,29465,ID-2015-BD116051-42248,2015-09-01,2015-09-04,Second Class,BD-116051,Brian Dahlen,Consumer,NaN,Herat,Hirat,Afghanistan,Southern Asia,Asia Pacific,OFF-SU-2988,"Acme Scissors, Easy Grip",Supplies,Office Supplies,243.54,9,0.0,104.49,18.72,Medium,2015,September,3 days
2,24598,IN-2017-CA120551-42816,2017-03-22,2017-03-29,Standard Class,CA-120551,Cathy Armstrong,Home Office,NaN,Herat,Hirat,Afghanistan,Southern Asia,Asia Pacific,TEC-MA-4211,"Epson Receipt Printer, White",Machines,Technology,346.32,3,0.0,13.77,14.10,Medium,2017,March,7 days
3,24597,IN-2017-CA120551-42816,2017-03-22,2017-03-29,Standard Class,CA-120551,Cathy Armstrong,Home Office,NaN,Herat,Hirat,Afghanistan,Southern Asia,Asia Pacific,FUR-FU-5726,"Rubbermaid Door Stop, Erganomic",Furnishings,Furniture,169.68,4,0.0,79.68,11.01,Medium,2017,March,7 days
4,29464,ID-2015-BD116051-42248,2015-09-01,2015-09-04,Second Class,BD-116051,Brian Dahlen,Consumer,NaN,Herat,Hirat,Afghanistan,Southern Asia,Asia Pacific,OFF-EN-3664,"Cameo Interoffice Envelope, with clear poly wi...",Envelopes,Office Supplies,203.88,4,0.0,24.36,5.72,Medium,2015,September,3 days