In [1]:
import pandas as pd

In [7]:
df = pd.read_excel(r"D:\Ai Ml learning\Pandas\.ipynb_checkpoints\ETH.xlsx")

In [15]:
df.dtypes

        Date  Symbol   Open     High     Low  Close       Volume
0 2020-03-13  ETHUSD  129.94  131.32  126.42  124.43  1842932.93
1 2020-03-13  ETHUSD  119.51  132.52  117.53  129.53  4233332.93
2 2020-03-13  ETHUSD  124.47  124.42  115.43  119.42  5347441.93
3 2020-03-13  ETHUSD  124.08  127.63  121.85  124.74  6347974.93
4 2020-03-13  ETHUSD  124.85  129.90  120.54  124.64  9482942.93

In [9]:
df.loc[0,'Date']

Timestamp('2020-03-13 00:00:00')

In [12]:
# # will cut from the end 6/1/1930 22:00 will be 22
# df.Date.str.slice(-5,-3).astype(int).head()
# better method is 
df['Date'] = pd.to_datetime(df.Date)
# it will change data type of date row into datetime type

In [17]:
df.Date.dt.weekday_name

AttributeError: 'DatetimeProperties' object has no attribute 'weekday_name'

In [18]:
df.Date.dt.weekday

0    4
1    4
2    4
3    4
4    4
Name: Date, dtype: int32

In [ ]:
df.Date.dt.dayofyear

In [21]:
# comparison
ts = pd.to_datetime('2020-03-13')

In [23]:
df.loc[df.Date >= ts,:]
# it will give us date bigger then ts date

        Date  Symbol   Open     High     Low  Close       Volume
0 2020-03-13  ETHUSD  129.94  131.32  126.42  124.43  1842932.93
1 2020-03-13  ETHUSD  119.51  132.52  117.53  129.53  4233332.93
2 2020-03-13  ETHUSD  124.47  124.42  115.43  119.42  5347441.93
3 2020-03-13  ETHUSD  124.08  127.63  121.85  124.74  6347974.93
4 2020-03-13  ETHUSD  124.85  129.90  120.54  124.64  9482942.93

In [25]:
df.Date.max() - df.Date.min()
df.Date.max() - df.Date.min().days

AttributeError: 'Timestamp' object has no attribute 'days'